<?php

namespace Database\Seeders;

use App\Models\Plant;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PlantSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::where('role', 'admin')->first();
        $editor = User::where('role', 'editor')->first();

        $plants = [
            // Antiinflamasi (cat 1)
            [
                'category_id'    => 1,
                'user_id'        => $admin->id,
                'local_name'     => 'Jahe',
                'latin_name'     => 'Zingiber officinale',
                'description'    => 'Jahe adalah tanaman rimpang yang sangat populer sebagai rempah-rempah dan bahan obat. Rimpangnya berwarna putih kekuningan dengan rasa pedas dan aroma yang khas.',
                'benefits'       => 'Meredakan mual dan muntah, mengurangi peradangan sendi, meredakan nyeri otot, meningkatkan sistem imun, membantu pencernaan, menghangatkan tubuh, dan mengurangi gejala flu.',
                'usage'          => 'Bisa dikonsumsi sebagai minuman jahe hangat, ditambahkan ke masakan, atau diolah menjadi wedang jahe. Untuk obat, iris 2-3 cm rimpang segar, rebus dengan 2 gelas air hingga tersisa 1 gelas, minum hangat 2x sehari.',
                'side_effects'   => 'Konsumsi berlebihan dapat menyebabkan mulas. Hindari jika memiliki gangguan pembekuan darah atau akan menjalani operasi.',
                'origin'         => 'Asia Tenggara',
                'harvest_season' => 'Sepanjang tahun',
                'status'         => 'published',
                'views'          => 1250,
            ],
            [
                'category_id'    => 1,
                'user_id'        => $editor->id,
                'local_name'     => 'Kunyit',
                'latin_name'     => 'Curcuma longa',
                'description'    => 'Kunyit adalah tanaman rempah-rempah asli Asia Selatan yang dikenal dengan warna kuning keemasannya. Rimpangnya mengandung kurkumin, senyawa bioaktif yang sangat berkhasiat.',
                'benefits'       => 'Antiinflamasi kuat, antioksidan tinggi, meningkatkan fungsi otak, menurunkan risiko penyakit jantung, membantu mencegah kanker, membantu mengatasi arthritis, dan memperbaiki gejala depresi.',
                'usage'          => 'Kunyit segar dapat diparut dan diperas untuk diambil airnya. Minum 1 sendok makan air kunyit dicampur madu dan air hangat setiap pagi. Bisa juga dijadikan bumbu masakan.',
                'side_effects'   => 'Dapat menyebabkan gangguan pencernaan jika dikonsumsi dalam jumlah besar. Tidak dianjurkan untuk ibu hamil dalam dosis tinggi.',
                'origin'         => 'India & Asia Tenggara',
                'harvest_season' => 'Sepanjang tahun',
                'status'         => 'published',
                'views'          => 980,
            ],
            // Antioksidan (cat 2)
            [
                'category_id'    => 2,
                'user_id'        => $admin->id,
                'local_name'     => 'Mengkudu',
                'latin_name'     => 'Morinda citrifolia',
                'description'    => 'Mengkudu atau pace adalah tanaman buah tropis yang tumbuh di Asia Selatan dan Tenggara. Buahnya memiliki aroma khas dan rasa pahit, namun mengandung banyak nutrisi berharga.',
                'benefits'       => 'Kaya antioksidan, membantu menurunkan tekanan darah, meningkatkan sistem imun, memiliki sifat antikanker, membantu mengatasi radang sendi, dan meningkatkan energi tubuh.',
                'usage'          => 'Buah mengkudu dapat diperas diambil airnya, dicampur madu untuk mengurangi rasa pahit. Minum 30-60 ml jus mengkudu setiap hari sebelum makan.',
                'side_effects'   => 'Mengandung kalium tinggi, hindari jika memiliki gangguan ginjal. Dapat berinteraksi dengan obat pengencer darah.',
                'origin'         => 'Asia Tenggara',
                'harvest_season' => 'Sepanjang tahun',
                'status'         => 'published',
                'views'          => 756,
            ],
            // Pencernaan (cat 3)
            [
                'category_id'    => 3,
                'user_id'        => $editor->id,
                'local_name'     => 'Temulawak',
                'latin_name'     => 'Curcuma xanthorrhiza',
                'description'    => 'Temulawak adalah tanaman asli Indonesia yang banyak tumbuh di Pulau Jawa. Rimpangnya berwarna kuning-jingga dengan kandungan kurkuminoid yang tinggi.',
                'benefits'       => 'Meningkatkan nafsu makan, membantu fungsi hati, melancarkan pencernaan, antiinflamasi, meningkatkan daya tahan tubuh, dan membantu mengatasi maag.',
                'usage'          => 'Rebus 25 gram rimpang temulawak segar yang sudah diiris dengan 600 ml air hingga tersisa 300 ml. Saring dan minum 2 kali sehari, pagi dan sore.',
                'side_effects'   => 'Konsumsi berlebihan dapat mengiritasi lambung. Tidak dianjurkan untuk penderita batu empedu.',
                'origin'         => 'Indonesia (Jawa)',
                'harvest_season' => 'Sepanjang tahun',
                'status'         => 'published',
                'views'          => 890,
            ],
            [
                'category_id'    => 3,
                'user_id'        => $admin->id,
                'local_name'     => 'Lidah Buaya',
                'latin_name'     => 'Aloe vera',
                'description'    => 'Lidah buaya adalah tanaman sukulen yang dikenal luas sebagai tanaman serbaguna. Gel dalam daunnya mengandung banyak senyawa bioaktif bermanfaat.',
                'benefits'       => 'Mempercepat penyembuhan luka, melembabkan kulit, membantu mengatasi sembelit, menurunkan kadar gula darah, memiliki sifat antibakteri, dan meredakan heartburn.',
                'usage'          => 'Ambil gel dari daun lidah buaya yang telah dikupas. Untuk pencernaan, minum 1-2 sendok makan gel murni. Untuk kulit, oleskan langsung pada area yang bermasalah.',
                'side_effects'   => 'Konsumsi oral berlebihan dapat menyebabkan diare. Hindari konsumsi oral selama kehamilan.',
                'origin'         => 'Afrika Utara',
                'harvest_season' => 'Sepanjang tahun',
                'status'         => 'published',
                'views'          => 1100,
            ],
            // Imun (cat 4)
            [
                'category_id'    => 4,
                'user_id'        => $editor->id,
                'local_name'     => 'Sambiloto',
                'latin_name'     => 'Andrographis paniculata',
                'description'    => 'Sambiloto adalah tanaman herbal yang sangat pahit, dikenal sebagai "Raja Pahit" di Asia. Kandungan andrografolid-nya memiliki banyak manfaat kesehatan.',
                'benefits'       => 'Meningkatkan daya tahan tubuh, antivirus dan antibakteri, membantu mengatasi flu dan demam, anti-HIV, antikanker, dan membantu mengontrol gula darah.',
                'usage'          => 'Rebus 3-5 gram daun sambiloto kering dengan 2 gelas air hingga tersisa 1 gelas. Minum 2 kali sehari. Atau konsumsi dalam bentuk kapsul ekstrak sambiloto.',
                'side_effects'   => 'Rasa sangat pahit. Dapat menurunkan tekanan darah dan gula darah secara signifikan. Hindari selama kehamilan.',
                'origin'         => 'India & Asia Tenggara',
                'harvest_season' => 'Sepanjang tahun',
                'status'         => 'published',
                'views'          => 620,
            ],
            [
                'category_id'    => 4,
                'user_id'        => $admin->id,
                'local_name'     => 'Meniran',
                'latin_name'     => 'Phyllanthus niruri',
                'description'    => 'Meniran adalah tanaman liar kecil yang tumbuh di daerah tropis. Seluruh bagian tanaman ini memiliki khasiat obat yang telah digunakan dalam pengobatan tradisional Ayurveda.',
                'benefits'       => 'Meningkatkan imunitas, membantu penyakit hati (hepatitis), diuretik alami, antioksidan, antivirus, dan membantu mengeluarkan batu ginjal.',
                'usage'          => 'Rebus seluruh tanaman meniran (±10 gram) yang segar atau kering dengan 2 gelas air. Saring dan minum 2-3 kali sehari. Bisa juga dikonsumsi dalam bentuk kapsul.',
                'side_effects'   => 'Umumnya aman. Konsumsi berlebihan dapat mengganggu fungsi ginjal pada beberapa orang.',
                'origin'         => 'Asia Tropis',
                'harvest_season' => 'Sepanjang tahun',
                'status'         => 'published',
                'views'          => 445,
            ],
            // Pernapasan (cat 5)
            [
                'category_id'    => 5,
                'user_id'        => $editor->id,
                'local_name'     => 'Kencur',
                'latin_name'     => 'Kaempferia galanga',
                'description'    => 'Kencur adalah tanaman rimpang asli Asia Tenggara yang sering digunakan dalam masakan dan pengobatan tradisional Indonesia. Aromanya khas dan menyegarkan.',
                'benefits'       => 'Meredakan batuk berdahak, mengobati radang tenggorokan, meredakan pegal linu, memperlancar pernafasan, dan meningkatkan nafsu makan.',
                'usage'          => 'Parut 1-2 rimpang kencur segar, peras airnya. Campurkan dengan madu dan sedikit garam, minum 2 kali sehari untuk meredakan batuk. Atau rebus rimpang kencur dan minum airnya.',
                'side_effects'   => 'Umumnya aman dikonsumsi. Dapat menyebabkan iritasi lambung jika dikonsumsi saat perut kosong.',
                'origin'         => 'Asia Tenggara',
                'harvest_season' => 'Sepanjang tahun',
                'status'         => 'published',
                'views'          => 534,
            ],
            // Jantung & Darah (cat 6)
            [
                'category_id'    => 6,
                'user_id'        => $admin->id,
                'local_name'     => 'Bawang Putih',
                'latin_name'     => 'Allium sativum',
                'description'    => 'Bawang putih adalah salah satu bumbu dapur paling umum di dunia, yang juga memiliki sejarah panjang sebagai obat herbal. Kandungan allicin-nya memberikan banyak manfaat kesehatan.',
                'benefits'       => 'Menurunkan tekanan darah, menurunkan kolesterol LDL, mencegah pembekuan darah, meningkatkan sistem imun, antibakteri alami, dan membantu mencegah kanker.',
                'usage'          => 'Konsumsi 1-2 siung bawang putih mentah setiap hari, atau cincang halus dan tambahkan ke masakan. Untuk hipertensi, bisa dibuat teh bawang putih dengan merebusnya bersama air dan madu.',
                'side_effects'   => 'Dapat menyebabkan bau mulut dan bau badan. Konsumsi mentah berlebihan dapat mengiritasi lambung.',
                'origin'         => 'Asia Tengah',
                'harvest_season' => 'Kering (musim kemarau)',
                'status'         => 'published',
                'views'          => 1560,
            ],
            // Kulit & Kecantikan (cat 7)
            [
                'category_id'    => 7,
                'user_id'        => $editor->id,
                'local_name'     => 'Pegagan',
                'latin_name'     => 'Centella asiatica',
                'description'    => 'Pegagan atau daun kaki kuda adalah tanaman herbal yang tumbuh di daerah tropis dan subtropis. Dikenal dalam pengobatan Ayurveda dan tradisional Asia sebagai tanaman peremajaan.',
                'benefits'       => 'Mempercepat penyembuhan luka dan bekas luka, meremajakan kulit, meningkatkan fungsi kognitif dan memori, meredakan kecemasan, dan meningkatkan sirkulasi darah.',
                'usage'          => 'Konsumsi daun pegagan segar sebagai lalapan atau dijus. Untuk kulit, tumbuk daun pegagan segar dan oleskan pada luka atau kulit bermasalah. Tersedia juga dalam kapsul suplemen.',
                'side_effects'   => 'Dapat menyebabkan kantuk pada beberapa orang. Hindari penggunaan berlebihan karena dapat mempengaruhi hati.',
                'origin'         => 'Asia & Afrika Selatan',
                'harvest_season' => 'Sepanjang tahun',
                'status'         => 'published',
                'views'          => 789,
            ],
            // Anti Diabetes (cat 8)
            [
                'category_id'    => 8,
                'user_id'        => $admin->id,
                'local_name'     => 'Pare',
                'latin_name'     => 'Momordica charantia',
                'description'    => 'Pare atau peria adalah tanaman sayuran tropis yang dikenal dengan rasa pahitnya. Selain sebagai sayuran, pare memiliki banyak manfaat kesehatan terutama untuk pengidap diabetes.',
                'benefits'       => 'Membantu menurunkan gula darah, meningkatkan produksi insulin, kaya vitamin C dan antioksidan, membantu menurunkan berat badan, antivirus, dan antibakteri.',
                'usage'          => 'Jus buah pare segar: blender 1 buah pare ukuran sedang dengan sedikit air, tambahkan jeruk nipis. Minum sebelum makan. Atau olah sebagai sayuran tumis sehari-hari.',
                'side_effects'   => 'Dapat menurunkan gula darah secara drastis pada penderita diabetes yang sudah mengonsumsi obat. Hindari selama kehamilan.',
                'origin'         => 'Asia Selatan & Tenggara',
                'harvest_season' => 'Sepanjang tahun',
                'status'         => 'published',
                'views'          => 678,
            ],
            [
                'category_id'    => 8,
                'user_id'        => $editor->id,
                'local_name'     => 'Kayu Manis',
                'latin_name'     => 'Cinnamomum verum',
                'description'    => 'Kayu manis adalah rempah yang berasal dari kulit kayu pohon Cinnamomum. Indonesia merupakan salah satu penghasil kayu manis terbesar di dunia.',
                'benefits'       => 'Membantu mengontrol gula darah, menurunkan kolesterol, antiinflamasi, antibakteri, kaya antioksidan, membantu meningkatkan sensitivitas insulin, dan meredakan nyeri haid.',
                'usage'          => 'Tambahkan 1/2 sendok teh bubuk kayu manis ke dalam teh atau kopi. Bisa juga direbus dengan air dan diminum sebagai teh kayu manis. Konsumsi 1-6 gram per hari.',
                'side_effects'   => 'Konsumsi berlebihan dapat menimbulkan kerusakan hati (terutama cassia cinnamon yang mengandung kumarin tinggi).',
                'origin'         => 'Sri Lanka & Indonesia',
                'harvest_season' => 'Sepanjang tahun',
                'status'         => 'published',
                'views'          => 543,
            ],
            // Antipiretik (cat 9)
            [
                'category_id'    => 9,
                'user_id'        => $admin->id,
                'local_name'     => 'Belimbing Wuluh',
                'latin_name'     => 'Averrhoa bilimbi',
                'description'    => 'Belimbing wuluh adalah buah tropis yang memiliki rasa sangat asam. Buah, daun, dan bunganya digunakan dalam pengobatan tradisional untuk berbagai penyakit.',
                'benefits'       => 'Menurunkan demam, membantu mengatasi batuk, menurunkan tekanan darah, membantu mengobati sariawan, antibakteri, dan membantu mengatasi rematik.',
                'usage'          => 'Rebus 5-6 buah belimbing wuluh dengan 2 gelas air, tambahkan gula merah dan sedikit garam. Saring dan minum 2 kali sehari untuk demam. Atau tempel daun yang sudah dilayukan pada dahi.',
                'side_effects'   => 'Rasa sangat asam dapat mengiritasi lambung. Penderita maag sebaiknya berhati-hati.',
                'origin'         => 'Asia Tenggara',
                'harvest_season' => 'Sepanjang tahun',
                'status'         => 'published',
                'views'          => 398,
            ],
            // Tonik & Stamina (cat 10)
            [
                'category_id'    => 10,
                'user_id'        => $editor->id,
                'local_name'     => 'Mahkota Dewa',
                'latin_name'     => 'Phaleria macrocarpa',
                'description'    => 'Mahkota dewa adalah tanaman asli Papua yang telah lama digunakan dalam pengobatan tradisional Indonesia. Buahnya mengandung berbagai senyawa bioaktif yang berkhasiat.',
                'benefits'       => 'Meningkatkan stamina, antiinflamasi, membantu mengobati diabetes, menurunkan tekanan darah, antikanker, membantu penyakit liver, dan meningkatkan sistem imun.',
                'usage'          => 'Iris tipis 5 buah mahkota dewa (tanpa biji yang beracun), keringkan. Rebus dengan 3 gelas air hingga tersisa 2 gelas. Minum 2 kali sehari setengah gelas.',
                'side_effects'   => 'Biji mahkota dewa beracun, jangan dikonsumsi. Penggunaan berlebihan dapat menyebabkan efek samping serius.',
                'origin'         => 'Papua, Indonesia',
                'harvest_season' => 'Sepanjang tahun',
                'status'         => 'published',
                'views'          => 312,
            ],
            [
                'category_id'    => 10,
                'user_id'        => $admin->id,
                'local_name'     => 'Ginseng Jawa',
                'latin_name'     => 'Talinum paniculatum',
                'description'    => 'Ginseng Jawa atau ginseng merah adalah tanaman herbal yang tumbuh subur di daerah tropis. Meskipun berbeda dengan ginseng Korea, tanaman ini memiliki khasiat yang tidak kalah baik.',
                'benefits'       => 'Meningkatkan stamina dan vitalitas, mengurangi kelelahan, meningkatkan libido, membantu pemulihan pasca sakit, dan meningkatkan sistem imun.',
                'usage'          => 'Rebus akar ginseng Jawa dengan air, minum sebagai teh. Bisa juga dijadikan bahan jamu tradisional bersama rempah lainnya. Konsumsi secara rutin untuk hasil optimal.',
                'side_effects'   => 'Umumnya aman. Hindari konsumsi berlebihan. Konsultasikan dengan dokter jika mengonsumsi obat-obatan tertentu.',
                'origin'         => 'Asia Tropis (Jawa)',
                'harvest_season' => 'Sepanjang tahun',
                'status'         => 'published',
                'views'          => 289,
            ],
            [
                'category_id'    => 2,
                'user_id'        => $editor->id,
                'local_name'     => 'Rosella',
                'latin_name'     => 'Hibiscus sabdariffa',
                'description'    => 'Rosella adalah tanaman berbunga dengan kelopak berwarna merah cerah yang kaya manfaat. Berasal dari Afrika Barat, kini banyak dibudidayakan di Indonesia.',
                'benefits'       => 'Kaya antioksidan flavonoid, menurunkan tekanan darah, menurunkan kolesterol, membantu menurunkan berat badan, anti-diabetes, dan memiliki sifat antibakteri.',
                'usage'          => 'Rendam 3-5 kelopak bunga rosella kering dalam air panas selama 5-10 menit. Tambahkan madu atau gula batu jika perlu. Minum 1-2 cangkir sehari.',
                'side_effects'   => 'Dapat menurunkan tekanan darah, pantau jika sudah mengonsumsi obat hipertensi. Hindari selama kehamilan dalam jumlah besar.',
                'origin'         => 'Afrika Barat',
                'harvest_season' => 'Musim hujan',
                'status'         => 'published',
                'views'          => 467,
            ],
            [
                'category_id'    => 7,
                'user_id'        => $admin->id,
                'local_name'     => 'Daun Sirih',
                'latin_name'     => 'Piper betle',
                'description'    => 'Daun sirih adalah tanaman merambat tropis yang telah digunakan selama berabad-abad dalam tradisi budaya dan pengobatan Asia. Daunnya mengandung minyak atsiri yang berkhasiat.',
                'benefits'       => 'Antiseptik alami, membantu mengobati infeksi jamur dan bakteri, menyehatkan gigi dan mulut, meredakan batuk, membantu penyembuhan luka, dan meredakan gatal.',
                'usage'          => 'Untuk kesehatan mulut: kunyah beberapa lembar daun sirih. Untuk luka: tumbuk daun sirih dan tempel pada luka. Untuk keputihan: rebus daun sirih dan gunakan air rebusannya untuk cebok.',
                'side_effects'   => 'Penggunaan jangka panjang dalam bentuk sirih dapat meningkatkan risiko kanker mulut. Gunakan secara bijak.',
                'origin'         => 'Asia Selatan & Tenggara',
                'harvest_season' => 'Sepanjang tahun',
                'status'         => 'published',
                'views'          => 823,
            ],
            [
                'category_id'    => 6,
                'user_id'        => $editor->id,
                'local_name'     => 'Seledri',
                'latin_name'     => 'Apium graveolens',
                'description'    => 'Seledri adalah sayuran yang juga memiliki banyak khasiat obat. Seluruh bagian tanaman ini, dari daun hingga biji, dapat dimanfaatkan untuk kesehatan.',
                'benefits'       => 'Menurunkan tekanan darah tinggi, kaya vitamin dan mineral, diuretik alami, antiinflamasi, membantu menurunkan kolesterol, dan menjaga kesehatan jantung.',
                'usage'          => 'Jus seledri: blender beberapa batang seledri dengan air, minum setiap pagi. Atau rebus daun seledri dengan air, minum sebagai teh. Bisa juga dikonsumsi langsung sebagai sayuran.',
                'side_effects'   => 'Alergi seledri cukup umum. Dapat meningkatkan sensitivitas kulit terhadap sinar matahari. Hindari dosis besar selama kehamilan.',
                'origin'         => 'Mediterania & Asia Tengah',
                'harvest_season' => 'Sepanjang tahun',
                'status'         => 'published',
                'views'          => 356,
            ],
            [
                'category_id'    => 5,
                'user_id'        => $admin->id,
                'local_name'     => 'Jeruk Nipis',
                'latin_name'     => 'Citrus aurantifolia',
                'description'    => 'Jeruk nipis adalah buah sitrus kecil yang kaya vitamin C. Di Indonesia, jeruk nipis digunakan secara luas tidak hanya sebagai bumbu masakan tetapi juga sebagai obat tradisional.',
                'benefits'       => 'Kaya vitamin C untuk imunitas, membantu mengatasi batuk dan flu, meredakan tenggorokan sakit, membantu pencernaan, detoksifikasi tubuh, dan membantu menurunkan berat badan.',
                'usage'          => 'Peras 1-2 buah jeruk nipis, tambahkan ke air hangat dan madu. Minum setiap pagi untuk menjaga kesehatan. Untuk batuk, campurkan dengan kecap dan madu.',
                'side_effects'   => 'Rasa asam dapat merusak email gigi jika dikonsumsi berlebihan. Dapat mengiritasi lambung yang sensitif.',
                'origin'         => 'Asia Tenggara',
                'harvest_season' => 'Sepanjang tahun',
                'status'         => 'published',
                'views'          => 914,
            ],
        ];

        foreach ($plants as $plant) {
            Plant::create(array_merge($plant, [
                'slug' => Str::slug($plant['local_name']) . '-' . rand(1000, 9999),
            ]));
        }
    }
}
